package com.cygproject.cygproject.dao.mapper;

import com.cygproject.cygproject.model.database.AppleProduct;
import com.cygproject.cygproject.model.database.AppleProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppleProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apple_product
     *
     * @mbggenerated
     */
    int countByExample(AppleProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apple_product
     *
     * @mbggenerated
     */
    int deleteByExample(AppleProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apple_product
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apple_product
     *
     * @mbggenerated
     */
    int insert(AppleProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apple_product
     *
     * @mbggenerated
     */
    int insertSelective(AppleProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apple_product
     *
     * @mbggenerated
     */
    List<AppleProduct> selectByExample(AppleProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apple_product
     *
     * @mbggenerated
     */
    AppleProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apple_product
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AppleProduct record, @Param("example") AppleProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apple_product
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AppleProduct record, @Param("example") AppleProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apple_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AppleProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apple_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AppleProduct record);
}