package com.cygproject.cygproject.model.database;

public class AppleProduct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apple_product.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apple_product.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apple_product.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apple_product.price
     *
     * @mbggenerated
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apple_product.bornDate
     *
     * @mbggenerated
     */
    private String borndate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apple_product.id
     *
     * @return the value of apple_product.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apple_product.id
     *
     * @param id the value for apple_product.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apple_product.name
     *
     * @return the value of apple_product.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apple_product.name
     *
     * @param name the value for apple_product.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apple_product.type
     *
     * @return the value of apple_product.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apple_product.type
     *
     * @param type the value for apple_product.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apple_product.price
     *
     * @return the value of apple_product.price
     *
     * @mbggenerated
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apple_product.price
     *
     * @param price the value for apple_product.price
     *
     * @mbggenerated
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apple_product.bornDate
     *
     * @return the value of apple_product.bornDate
     *
     * @mbggenerated
     */
    public String getBorndate() {
        return borndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apple_product.bornDate
     *
     * @param borndate the value for apple_product.bornDate
     *
     * @mbggenerated
     */
    public void setBorndate(String borndate) {
        this.borndate = borndate == null ? null : borndate.trim();
    }
}